=== YassineOuahidi/waltid-ssikit-vclib/src/test/resources/schemas/VerifiableMandate.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialStatus" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "holder" : {
          "type" : "object",
          "properties" : {
            "constraints" : {
              "type" : "object",
              "properties" : {
                "boundaries" : {
                  "type" : "string"
                },
                "circumstances" : {
                  "type" : "string"
                },
                "endTime" : {
                  "type" : "string"
                },
                "pointOfOrigin" : {
                  "type" : "string"
                },
                "radiusKm" : {
                  "type" : "string"
                },
                "startTime" : {
                  "type" : "string"
                }
              },
              "additionalProperties" : false
            },
            "id" : {
              "type" : "string"
            },
            "role" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "id" : {
          "type" : "string"
        },
        "proxied" : {
          "type" : "object",
          "properties" : {
            "id" : {
              "type" : "string"
            },
            "permissions" : {
              "type" : "object",
              "properties" : {
                "grant" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string"
                  }
                },
                "when" : {
                  "type" : "object",
                  "properties" : {
                    "role" : {
                      "type" : "string"
                    }
                  },
                  "additionalProperties" : false
                }
              },
              "additionalProperties" : false
            }
          },
          "additionalProperties" : false
        }
      },
      "additionalProperties" : false
    },
    "evidence" : {
      "type" : "object",
      "properties" : {
        "documentPresence" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "evidenceDocument" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "id" : {
          "type" : "string"
        },
        "subjectPresence" : {
          "type" : "string"
        },
        "type" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "verifier" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "string"
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== YassineOuahidi/waltid-ssikit-vclib/src/test/resources/serialized/VerifiableMandate.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "credentialSchema": {
    "id": "https://api.preprod.ebsi.eu/trusted-schemas-registry/v1/schemas/0x2488fd38783d65e4fd46e7889eb113743334dbc772b05df382b8eadce763101b",
    "type": "JsonSchemaValidator2018"
  },
  "credentialStatus": {
    "id": "https://api.preprod.ebsi.eu/status/identity#verifiableMandate#51e42fda-cb0a-4333-b6a6-35cb147e1a88",
    "type": "CredentialsStatusList2020"
  },
  "credentialSubject": {
    "holder": {
      "constraints": {
        "boundaries": "",
        "circumstances": "",
        "endTime": "",
        "pointOfOrigin": "",
        "radiusKm": "",
        "startTime": ""
      },
      "id": "",
      "role": ""
    },
    "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
    "proxied": {
      "id": "did:ebsi:zgqR3EoNy6WuDkSs1kM8jtH",
      "permissions": {
        "grant": [
          "sign",
          "enroll"
        ],
        "when": {
          "role": "family"
        }
      }
    }
  },
  "evidence": {
    "documentPresence": [
      "Physical"
    ],
    "evidenceDocument": [
      "https://essif.europa.eu/tsr-va/evidence/f2aeec97-fc0d-42bf-8ca7-0548192d5678"
    ],
    "id": "https://essif.europa.eu/tsr-va/evidence/f2aeec97-fc0d-42bf-8ca7-0548192d5678",
    "subjectPresence": "Physical",
    "type": [
      "DocumentVerification"
    ],
    "verifier": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN"
  },
  "id": "identity#verifiableMandateID#698243e9-eef4-4a21-90be-f5f84b64cacd",
  "issuanceDate": "2021-08-31T00:00:00Z",
  "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
  "validFrom": "2021-08-31T00:00:00Z",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableMandate"
  ]
}
